// <auto-generated />
using AutoszereloMuhely.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoszereloMuhely.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408084854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AutoszereloMuhely.Models.Munka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allapot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GyartasiEv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HibaLeiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HibaSulyossag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Munkak");
                });

            modelBuilder.Entity("AutoszereloMuhely.Models.Ugyfel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ugyfelek");
                });

            modelBuilder.Entity("AutoszereloMuhely.Models.Munka", b =>
                {
                    b.HasOne("AutoszereloMuhely.Models.Ugyfel", "Ugyfel")
                        .WithMany("Munkak")
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ugyfel");
                });

            modelBuilder.Entity("AutoszereloMuhely.Models.Ugyfel", b =>
                {
                    b.Navigation("Munkak");
                });
#pragma warning restore 612, 618
        }
    }
}
